# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:
  REDIS_HOST: "stagedrinkeby-001.avqgak.0001.use1.cache.amazonaws.com"
  REDIS_PORT: 6379
  INFURA_HTTP_PROVIDER: "https://rinkeby.infura.io/v3/5eb45628ce2c4ecebcce7f201f352792"
  MNEMONIC: "knee violin certain rebuild rival couch wonder bind bridge delay tourist poet"
  RELAYER_ACC_INDEX: 0
  RELAY_TIMEOUT: 60*60*60
  STANDARD_BOUNTIES_ADDRESS: "0x38F1886081759F7D352c28984908D04e8D2205A6"
  BOUNTIES_METATX_RELAYER_ADDRESS: "0x0d12b3fa96b3aacedd06aba62c17cb5fc0e17627"
  NO_ETH_USER_PK: "1f3c30d405a6d1f9694007f3a56c7cf4d3852dbfeaa297bc777d6d86636b203d"

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: standardbounties-relayer
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
