# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 802922962628.dkr.ecr.us-east-1.amazonaws.com/bounties-network/standardbounties-relayer
  tag: 0.0.25
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:
  INFURA_HTTP_PROVIDER: "https://rinkeby.infura.io/v3/5eb45628ce2c4ecebcce7f201f352792"
  MNEMONIC: "knee violin certain rebuild rival couch wonder bind bridge delay tourist poet"
  RELAYER_ACC_INDEX: 0
  STANDARD_BOUNTIES_ADDRESS: "0x38F1886081759F7D352c28984908D04e8D2205A6"
  BOUNTIES_METATX_RELAYER_ADDRESS: "0x0d45e1f2cb1f28c05c9feee7d771a5acb2f237f5"
  PORT: 3001
  RELAY_TIMEOUT: 120
  REDIS_HOST: "stagedrinkeby-001.avqgak.0001.use1.cache.amazonaws.com"
  REDIS_PORT: 6379
  NO_ETH_USER_PK: "cfbf14398fa6119d9495474235dce1353c27adb5476bb457bf20b93f4954b79a"
  ROLLBAR_ACCESS_TOKEN: "d3be6f4f72d044f696c9e9978611f8ac"

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: standardbounties-relayer
  type: ClusterIP
  externalPort: 80
  internalPort: 3001
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
